import json, urllib.request, os, sys

MAX_ROUNDS = 5

def post_comment(body):
    token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    pr_number = os.environ.get("PR_NUMBER", "")
    if not token or not repo or not pr_number:
        print("Missing env vars for posting comment")
        return
    data = json.dumps({"body": body}).encode()
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    req = urllib.request.Request(url, data=data, headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json"
    })
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"Posted comment: {resp.status}")
    except Exception as e:
        print(f"Failed to post comment: {e}")

def call_api(url, data, headers):
    req = urllib.request.Request(url, data=data, headers=headers)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except Exception as e:
        return {"error": str(e)}

def parse_verdict(text):
    """Extract APPROVE or REQUEST_CHANGES from AI response."""
    upper = text.upper()
    if "APPROVE" in upper:
        return "APPROVE"
    elif "REQUEST_CHANGES" in upper or "REJECT" in upper or "CHANGES" in upper:
        return "REQUEST_CHANGES"
    return "UNKNOWN"

# Read diff
with open("/tmp/pr.diff") as f:
    diff = f.read()

round_history = []
all_approved = False
final_round = 0

for round_num in range(1, MAX_ROUNDS + 1):
    print(f"\n{'='*50}")
    print(f"ROUND {round_num}/{MAX_ROUNDS}")
    print(f"{'='*50}")

    # Build context from previous rounds
    if round_num == 1:
        prev_context = ""
    else:
        prev_context = "Previous review rounds:\n"
        for entry in round_history:
            prev_context += entry + "\n\n"

    # ============================================================
    # 1. Mimo Review
    # ============================================================
    print(f"Running Mimo review (round {round_num})...")
    if round_num == 1:
        mimo_prompt = (
            "You are an expert code reviewer. Review this PR diff. "
            "Format: SUMMARY / ISSUES (with severity CRITICAL/HIGH/MEDIUM/LOW) / VERDICT (APPROVE or REQUEST_CHANGES).\n\nDiff:\n"
            + diff
        )
    else:
        mimo_prompt = (
            f"You are an expert code reviewer. Previous rounds found issues. "
            f"Review this PR diff again considering the feedback below.\n\n"
            f"{prev_context}\n"
            f"Current Diff:\n{diff}\n\n"
            f"Format: SUMMARY / ISSUES (with severity) / VERDICT (APPROVE or REQUEST_CHANGES)."
        )

    mimo_data = json.dumps({
        "model": "mimo-v2.5-pro",
        "max_tokens": 1000,
        "messages": [{"role": "user", "content": mimo_prompt}]
    }).encode()

    mimo_key = os.environ.get("MIMO_API_KEY", "")
    mimo_result = call_api(
        "https://api.xiaomimimo.com/anthropic/v1/messages",
        mimo_data,
        {
            "Content-Type": "application/json",
            "x-api-key": mimo_key,
            "anthropic-version": "2023-06-01"
        }
    )

    mimo_text = ""
    if mimo_result.get("content"):
        mimo_text = mimo_result["content"][0]["text"]
    else:
        mimo_text = f"Mimo error: {mimo_result.get('error', 'unknown')}"
    mimo_verdict = parse_verdict(mimo_text)
    print(f"Mimo round {round_num}: {mimo_verdict} - {mimo_text[:80]}")

    post_comment(f"## Mimo Review (Round {round_num}) — {mimo_verdict}\n\n```\n{mimo_text}\n```\n\n*Generated by Mimo AI*")
    round_history.append(f"[Round {round_num}] Mimo ({mimo_verdict}): {mimo_text[:300]}")

    # ============================================================
    # 2. Agnes AI Review
    # ============================================================
    print(f"Running Agnes AI review (round {round_num})...")
    if round_num == 1:
        agnes_prompt = (
            f"You are an expert code reviewer. Mimo AI already reviewed this PR below. "
            f"Provide your own independent analysis.\n\nMimo review:\n{mimo_text}\n\nDiff:\n{diff}"
        )
    else:
        agnes_prompt = (
            f"You are an expert code reviewer. Previous rounds found issues. "
            f"Review this PR diff again considering all feedback.\n\n{prev_context}\n"
            f"Mimo (latest):\n{mimo_text}\n\nDiff:\n{diff}"
        )

    agnes_data = json.dumps({
        "model": "agnes-2.0-flash",
        "messages": [{"role": "user", "content": agnes_prompt}]
    }).encode()

    agnes_key = os.environ.get("AGNES_API_KEY", "")
    agnes_result = call_api(
        "https://apihub.agnes-ai.com/v1/chat/completions",
        agnes_data,
        {
            "Content-Type": "application/json",
            "Authorization": agnes_key
        }
    )

    agnes_text = ""
    if agnes_result.get("choices"):
        agnes_text = agnes_result["choices"][0]["message"]["content"]
    else:
        agnes_text = f"Agnes AI error: {agnes_result.get('error', 'unknown')}"
    agnes_verdict = parse_verdict(agnes_text)
    print(f"Agnes AI round {round_num}: {agnes_verdict} - {agnes_text[:80]}")

    post_comment(f"## Agnes AI Review (Round {round_num}) — {agnes_verdict}\n\n```\n{agnes_text}\n```\n\n*Generated by Agnes AI*")
    round_history.append(f"[Round {round_num}] Agnes AI ({agnes_verdict}): {agnes_text[:300]}")

    # ============================================================
    # 3. StepFun (Claude) Review
    # ============================================================
    print(f"Running Claude (StepFun) review (round {round_num})...")
    if round_num == 1:
        stepfun_prompt = (
            f"You are an expert code reviewer. Mimo AI and Agnes AI already reviewed this PR below. "
            f"Provide your final analysis considering both reviews.\n\n"
            f"Mimo review:\n{mimo_text}\n\nAgnes AI review:\n{agnes_text}\n\nDiff:\n{diff}"
        )
    else:
        stepfun_prompt = (
            f"You are an expert code reviewer. Previous rounds found issues. "
            f"Review this PR diff again considering all feedback.\n\n{prev_context}\n"
            f"Mimo (latest):\n{mimo_text}\n\nAgnes AI (latest):\n{agnes_text}\n\nDiff:\n{diff}"
        )

    stepfun_data = json.dumps({
        "model": "step-3.7-flash",
        "messages": [{"role": "user", "content": stepfun_prompt}]
    }).encode()

    stepfun_key = os.environ.get("STEPFUN_API_KEY", "")
    stepfun_result = call_api(
        "https://api.stepfun.com/step_plan/v1/chat/completions",
        stepfun_data,
        {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {stepfun_key}"
        }
    )

    stepfun_text = ""
    if stepfun_result.get("choices"):
        stepfun_text = stepfun_result["choices"][0]["message"]["content"]
    else:
        stepfun_text = f"StepFun error: {stepfun_result.get('error', 'unknown')}"
    stepfun_verdict = parse_verdict(stepfun_text)
    print(f"StepFun round {round_num}: {stepfun_verdict} - {stepfun_text[:80]}")

    post_comment(f"## Claude Review (Round {round_num}) — {stepfun_verdict}\n\n```\n{stepfun_text}\n```\n\n*Generated by Claude via StepFun*")
    round_history.append(f"[Round {round_num}] Claude ({stepfun_verdict}): {stepfun_text[:300]}")

    # ============================================================
    # Check if all approved
    # ============================================================
    final_round = round_num
    if mimo_verdict == "APPROVE" and agnes_verdict == "APPROVE" and stepfun_verdict == "APPROVE":
        all_approved = True
        print(f"\nAll 3 AIs APPROVED in round {round_num}! Review complete.")
        break
    else:
        print(f"\nNot all approved in round {round_num}. Mimo={mimo_verdict}, Agnes={agnes_verdict}, Claude={stepfun_verdict}")

# ============================================================
# Summary
# ============================================================
if all_approved:
    summary = f"All three AIs **APPROVED** this PR in round {final_round}/{MAX_ROUNDS}!\n\nIterative review converged successfully."
else:
    summary = f"Review stopped after {MAX_ROUNDS} rounds. Not all AIs approved.\n\nMimo and Agnes AI and Claude did not reach consensus."

post_comment(f"## AI Collaborative Review - Summary\n\n{summary}\n\nSee individual round comments above for details.\n\n*Mimo + Agnes AI + Claude iterative collaborative review*")

print("\nAll done!")
