import json, urllib.request, os, sys

def post_comment(body):
    token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    pr_number = os.environ.get("PR_NUMBER", "")
    if not token or not repo or not pr_number:
        print("Missing env vars for posting comment")
        return
    data = json.dumps({"body": body}).encode()
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    req = urllib.request.Request(url, data=data, headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json"
    })
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"Posted comment: {resp.status}")
    except Exception as e:
        print(f"Failed to post comment: {e}")

def call_api(url, data, headers):
    req = urllib.request.Request(url, data=data, headers=headers)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except Exception as e:
        return {"error": str(e)}

# Read diff
with open("/tmp/pr.diff") as f:
    diff = f.read()

# ============================================================
# 1. Gemini Review
# ============================================================
print("Running Gemini review...")
gemini_prompt = "You are an expert code reviewer. Review this PR diff. Format: SUMMARY / ISSUES (with severity) / VERDICT.\n\nDiff:\n" + diff
gemini_data = json.dumps({
    "contents": [{"parts": [{"text": gemini_prompt}]}]
}).encode()

gemini_key = os.environ.get("GEMINI_API_KEY", "")
gemini_result = call_api(
    f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key={gemini_key}",
    gemini_data,
    {"Content-Type": "application/json"}
)

gemini_text = ""
if gemini_result.get("candidates"):
    gemini_text = gemini_result["candidates"][0]["content"]["parts"][0]["text"]
else:
    gemini_text = f"Gemini error: {gemini_result.get('error', 'unknown')}"
print(f"Gemini done: {gemini_text[:100]}")

post_comment(f"## Gemini Code Review\n\n```\n{gemini_text}\n```\n\n*Generated by Gemini AI*")

# ============================================================
# 2. Agnes AI Review
# ============================================================
print("Running Agnes AI review...")
agnes_prompt = f"You are an expert code reviewer. Gemini already reviewed this PR below. Provide your own independent analysis.\n\nGemini review:\n{gemini_text}\n\nDiff:\n{diff}"

agnes_data = json.dumps({
    "model": "agnes-2.0-flash",
    "messages": [{"role": "user", "content": agnes_prompt}]
}).encode()

agnes_key = os.environ.get("AGNES_API_KEY", "")
agnes_result = call_api(
    "https://apihub.agnes-ai.com/v1/chat/completions",
    agnes_data,
    {
        "Content-Type": "application/json",
        "Authorization": agnes_key
    }
)

agnes_text = ""
if agnes_result.get("choices"):
    agnes_text = agnes_result["choices"][0]["message"]["content"]
else:
    agnes_text = f"Agnes AI error: {agnes_result.get('error', 'unknown')}"
print(f"Agnes AI done: {agnes_text[:100]}")

post_comment(f"## Agnes AI Code Review\n\n```\n{agnes_text}\n```\n\n*Generated by Agnes AI*")

# ============================================================
# 3. StepFun (Claude) Review
# ============================================================
print("Running Claude (StepFun) review...")
stepfun_prompt = f"You are an expert code reviewer. Gemini and Agnes AI already reviewed this PR below. Provide your own analysis considering both reviews.\n\nGemini review:\n{gemini_text}\n\nAgnes AI review:\n{agnes_text}\n\nDiff:\n{diff}"

stepfun_data = json.dumps({
    "model": "step-3.7-flash",
    "messages": [{"role": "user", "content": stepfun_prompt}]
}).encode()

stepfun_key = os.environ.get("STEPFUN_API_KEY", "")
stepfun_result = call_api(
    "https://api.stepfun.com/step_plan/v1/chat/completions",
    stepfun_data,
    {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {stepfun_key}"
    }
)

stepfun_text = ""
if stepfun_result.get("choices"):
    stepfun_text = stepfun_result["choices"][0]["message"]["content"]
else:
    stepfun_text = f"StepFun error: {stepfun_result.get('error', 'unknown')}"
print(f"StepFun done: {stepfun_text[:100]}")

post_comment(f"## Claude Review (StepFun)\n\n```\n{stepfun_text}\n```\n\n*Generated by Claude via StepFun*")

# ============================================================
# 4. Summary
# ============================================================
post_comment("## AI Collaborative Review - Summary\n\nAll three AIs have reviewed this PR:\n\n1. **Gemini** - Initial review\n2. **Agnes AI** - Independent analysis\n3. **Claude (StepFun)** - Final analysis considering all reviews\n\nSee individual comments above for details.\n\n*Gemini + Agnes AI + Claude collaborative review*")

print("All done!")
