"""
快乐8 AI 协同分析
三个 AI 协作分析彩票数据，循环最多5轮直到达成共识
"""

import json, urllib.request, os, sys

MAX_ROUNDS = 5

def post_comment(body):
    token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    pr_number = os.environ.get("PR_NUMBER", "")
    if not token or not repo or not pr_number:
        print("Missing env vars for posting comment")
        return
    data = json.dumps({"body": body}).encode()
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    req = urllib.request.Request(url, data=data, headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json"
    })
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"Posted comment: {resp.status}")
    except Exception as e:
        print(f"Failed to post comment: {e}")

def call_api(url, data, headers):
    req = urllib.request.Request(url, data=data, headers=headers)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except Exception as e:
        return {"error": str(e)}

def get_previous_reviews(token, repo):
    """获取之前的分析评论作为记忆"""
    url = f"https://api.github.com/repos/{repo}/issues/comments?per_page=100&sort=created&direction=desc"
    req = urllib.request.Request(url, headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    })
    try:
        with urllib.request.urlopen(req) as resp:
            comments = json.loads(resp.read())
            ai_comments = [c for c in comments if "Generated by" in c.get("body", "")]
            if ai_comments:
                memory = "## 过往分析记忆（最近评论）:\n\n"
                for c in reversed(ai_comments[-20:]):
                    body = c["body"][:5000]
                    memory += f"### {c['user']['login']}:\n{body}\n\n"
                return memory
    except Exception as e:
        print(f"Failed to fetch memory: {e}")
    return ""

# 读取数据
with open("/tmp/happy8_data.csv") as f:
    lines = f.readlines()
header = lines[0].strip()
data_lines = [l.strip() for l in lines[1:] if l.strip()]

# 解析数据
data_by_period = {}
for line in data_lines:
    parts = line.split(",")
    period = parts[0]
    date = parts[1]
    numbers = list(map(int, parts[2:]))
    data_by_period[period] = {"date": date, "numbers": sorted(numbers)}

latest_period = max(data_by_period.keys())
latest = data_by_period[latest_period]
latest_numbers = latest["numbers"]
latest_date = latest["date"]

# 读取用户问题
with open("/tmp/lottery_question.txt") as f:
    user_question = f.read().strip()

# 构建数据摘要
data_summary_lines = []
for period in sorted(data_by_period.keys()):
    nums = data_by_period[period]["numbers"]
    data_summary_lines.append(f"{period}: {nums}")
data_summary = "\n".join(data_summary_lines[-50:])  # 最近50期

# 加载记忆
token = os.environ.get("GITHUB_TOKEN", "")
repo = os.environ.get("GITHUB_REPOSITORY", "")
memory = get_previous_reviews(token, repo)
if not memory:
    memory = "（暂无过往分析记录）"

round_history = []
all_agreed = False
final_round = 0

for round_num in range(1, MAX_ROUNDS + 1):
    print(f"\n{'='*50}")
    print(f"ANALYSIS ROUND {round_num}/{MAX_ROUNDS}")
    print(f"{'='*50}")

    # 构建上下文
    if round_num == 1:
        prev_context = ""
    else:
        prev_context = "Previous analysis rounds:\n"
        for entry in round_history:
            prev_context += entry + "\n\n"

    # ============================================================
    # 1. Mimo 分析
    # ============================================================
    print(f"Running Mimo analysis (round {round_num})...")
    if round_num == 1:
        mimo_prompt = (
            f"你是一位专业的彩票数据分析专家。请用中文分析以下快乐8彩票数据。\n\n"
            f"用户问题：{user_question}\n\n"
            f"最新一期（{latest_period}期，{latest_date}）开奖号码：{latest_numbers}\n\n"
            f"历史数据（最近50期）：\n{data_summary}\n\n"
            f"过往分析记忆：\n{memory}\n\n"
            f"请用中文输出：\n"
            f"## 数据概览\n"
            f"## 尾数规律分析\n"
            f"## 网格位置分析（8列x10行）\n"
            f"## 连号分析\n"
            f"## 热号/冷号分析\n"
            f"## 规律总结\n"
            f"## 下期推荐号码\n"
            f"## 结论"
        )
    else:
        mimo_prompt = (
            f"你是一位专业的彩票数据分析专家。上一轮分析后，用户有新的追问。\n\n"
            f"用户问题：{user_question}\n\n"
            f"过往分析记忆：\n{memory}\n\n"
            f"上一轮分析：\n{prev_context}\n\n"
            f"最新一期（{latest_period}期）号码：{latest_numbers}\n\n"
            f"请基于以上所有信息，继续深入分析用户的问题。用中文输出。"
        )

    mimo_data = json.dumps({
        "model": "mimo-v2.5-pro",
        "max_tokens": 2000,
        "messages": [{"role": "user", "content": mimo_prompt}]
    }).encode()

    mimo_key = os.environ.get("MIMO_API_KEY", "")
    mimo_result = call_api(
        "https://api.xiaomimimo.com/anthropic/v1/messages",
        mimo_data,
        {
            "Content-Type": "application/json",
            "x-api-key": mimo_key,
            "anthropic-version": "2023-06-01"
        }
    )

    mimo_text = ""
    if mimo_result.get("content"):
        mimo_text = mimo_result["content"][0]["text"]
    else:
        mimo_text = f"Mimo 分析出错: {mimo_result.get('error', 'unknown')}"
    print(f"Mimo round {round_num} done: {mimo_text[:80]}")

    post_comment(f"## Mimo 分析 (第 {round_num} 轮)\n\n```\n{mimo_text}\n```\n\n*由 Mimo AI 生成*")
    round_history.append(f"[Round {round_num}] Mimo: {mimo_text[:500]}")

    # ============================================================
    # 2. Agnes AI 分析
    # ============================================================
    print(f"Running Agnes AI analysis (round {round_num})...")
    if round_num == 1:
        agnes_prompt = (
            f"你是一位专业的彩票数据分析专家。Mimo AI 已经分析了以下快乐8数据，请给出你独立的分析和验证。\n\n"
            f"用户问题：{user_question}\n\n"
            f"过往分析记忆：\n{memory}\n\n"
            f"Mimo 的分析结果：\n{mimo_text}\n\n"
            f"最新一期（{latest_period}期）号码：{latest_numbers}\n\n"
            f"历史数据（最近50期）：\n{data_summary}\n\n"
            f"请用中文独立分析，验证或补充 Mimo 的发现，给出你的结论。"
        )
    else:
        agnes_prompt = (
            f"你是一位专业的彩票数据分析专家。请继续分析用户的追问。\n\n"
            f"用户问题：{user_question}\n\n"
            f"过往分析记忆：\n{memory}\n\n"
            f"{prev_context}\n"
            f"Mimo 最新分析：\n{mimo_text}\n\n"
            f"请用中文继续深入分析。"
        )

    agnes_data = json.dumps({
        "model": "agnes-2.0-flash",
        "messages": [{"role": "user", "content": agnes_prompt}]
    }).encode()

    agnes_key = os.environ.get("AGNES_API_KEY", "")
    agnes_result = call_api(
        "https://apihub.agnes-ai.com/v1/chat/completions",
        agnes_data,
        {
            "Content-Type": "application/json",
            "Authorization": agnes_key
        }
    )

    agnes_text = ""
    if agnes_result.get("choices"):
        agnes_text = agnes_result["choices"][0]["message"]["content"]
    else:
        agnes_text = f"Agnes AI 分析出错: {agnes_result.get('error', 'unknown')}"
    print(f"Agnes AI round {round_num} done: {agnes_text[:80]}")

    post_comment(f"## Agnes AI 分析 (第 {round_num} 轮)\n\n```\n{agnes_text}\n```\n\n*由 Agnes AI 生成*")
    round_history.append(f"[Round {round_num}] Agnes AI: {agnes_text[:500]}")

    # ============================================================
    # 3. Claude (StepFun) 综合结论
    # ============================================================
    print(f"Running Claude analysis (round {round_num})...")
    if round_num == 1:
        stepfun_prompt = (
            f"你是一位专业的彩票数据分析专家。Mimo AI 和 Agnes AI 已经分析了以下快乐8数据，请综合所有分析结果给出最终结论。\n\n"
            f"用户问题：{user_question}\n\n"
            f"过往分析记忆：\n{memory}\n\n"
            f"Mimo 分析：\n{mimo_text}\n\n"
            f"Agnes AI 分析：\n{agnes_text}\n\n"
            f"最新一期（{latest_period}期）号码：{latest_numbers}\n\n"
            f"历史数据（最近50期）：\n{data_summary}\n\n"
            f"请用中文综合所有分析，给出：\n"
            f"1. 各方分析的共识和分歧\n"
            f"2. 最终结论\n"
            f"3. 下期重点关注号码\n"
            f"4. 风险提醒"
        )
    else:
        stepfun_prompt = (
            f"你是一位专业的彩票数据分析专家。请继续分析用户的追问。\n\n"
            f"用户问题：{user_question}\n\n"
            f"过往分析记忆：\n{memory}\n\n"
            f"{prev_context}\n"
            f"Mimo 最新分析：\n{mimo_text}\n\n"
            f"Agnes AI 最新分析：\n{agnes_text}\n\n"
            f"请用中文综合所有信息，给出深入分析。"
        )

    stepfun_data = json.dumps({
        "model": "step-3.7-flash",
        "messages": [{"role": "user", "content": stepfun_prompt}]
    }).encode()

    stepfun_key = os.environ.get("STEPFUN_API_KEY", "")
    stepfun_result = call_api(
        "https://api.stepfun.com/step_plan/v1/chat/completions",
        stepfun_data,
        {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {stepfun_key}"
        }
    )

    stepfun_text = ""
    if stepfun_result.get("choices"):
        stepfun_text = stepfun_result["choices"][0]["message"]["content"]
    else:
        stepfun_text = f"Claude 分析出错: {stepfun_result.get('error', 'unknown')}"
    print(f"Claude round {round_num} done: {stepfun_text[:80]}")

    post_comment(f"## Claude 综合分析 (第 {round_num} 轮)\n\n```\n{stepfun_text}\n```\n\n*由 Claude via StepFun 生成*")
    round_history.append(f"[Round {round_num}] Claude: {stepfun_text[:500]}")

    # ============================================================
    # 汇总评论
    # ============================================================
    final_round = round_num
    summary = (
        f"## 快乐8 AI 协同分析 — 第 {round_num} 轮汇总\n\n"
        f"**最新期**: {latest_period}期 ({latest_date})\n"
        f"**开奖号码**: {latest_numbers}\n\n"
        f"**三轮分析完成**:\n"
        f"1. Mimo — 数据规律分析\n"
        f"2. Agnes AI — 独立验证分析\n"
        f"3. Claude — 综合分析结论\n\n"
        f"详见上方各轮详细分析。\n\n"
        f"*Mimo + Agnes AI + Claude 快乐8协同分析*"
    )
    post_comment(summary)

    print(f"\nRound {round_num} complete.")

print("\nAll analysis rounds completed!")
print(f"Total rounds: {final_round}/{MAX_ROUNDS}")
